//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kaedei.AcPlay.Redirector
{


	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class acplayres {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal acplayres() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kaedei.AcPlay.Redirector.acplayres", typeof(acplayres).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;acplay&quot;,&quot;acdown&quot;].
        /// </summary>
        internal static string acfunban {
            get {
                return ResourceManager.GetString("acfunban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;uid&quot;:10000,&quot;id&quot;:10000,&quot;lasttime&quot;:-555980,&quot;vtype&quot;:&quot;sina&quot;,&quot;aid&quot;:10000,&quot;comment&quot;:0,&quot;vurl&quot;:&quot;10000&quot;,&quot;vid&quot;:&quot;10000&quot;,&quot;cid&quot;:&quot;10000&quot;,&quot;success&quot;:true,&quot;info&quot;:&quot;视频获取成功&quot;}.
        /// </summary>
        internal static string acfungetvideobyid {
            get {
                return ResourceManager.GetString("acfungetvideobyid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;AcPlay&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;embed width=&quot;100%&quot; height=&quot;100%&quot; id=&quot;ACFlashPlayer&quot; 
        ///	pluginspage=&quot;http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&quot; 
        ///	src=&quot;{PLAYER}?vid=10000&amp;type=video&amp;sort=new&quot; 
        ///	type=&quot;application/x- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string acfunhtml {
            get {
                return ResourceManager.GetString("acfunhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;y&quot;:1,&quot;height&quot;:1,&quot;x&quot;:1,&quot;width&quot;:1,&quot;url&quot;:&quot;&quot;}.
        /// </summary>
        internal static string acfunnewad {
            get {
                return ResourceManager.GetString("acfunnewad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;sc3yk793ea976&quot;,&quot;200108&quot;,&quot;2qo5k6f00ed8f&quot;,&quot;41ak1916930066&quot;].
        /// </summary>
        internal static string acfunu {
            get {
                return ResourceManager.GetString("acfunu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string acfunupdatevideobycontentid {
            get {
                return ResourceManager.GetString("acfunupdatevideobycontentid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;hasBuy&gt;true&lt;/hasBuy&gt;&lt;accept&gt;true&lt;/accept&gt;.
        /// </summary>
        internal static string bilibiliadvancecomment {
            get {
                return ResourceManager.GetString("bilibiliadvancecomment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;t&quot;:{&quot;keyword&quot;:[{&quot;value&quot;:&quot;heizi&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;xpkzxycy&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;saddddddddddddddddd&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;saddasdsad&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;sadasdas&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;yoooo&quot;,&quot;cnt&quot;:&quot;79&quot;},{&quot;value&quot;:&quot;FFFFF&quot;,&quot;cnt&quot;:&quot;24&quot;},{&quot;value&quot;:&quot;12dora&quot;,&quot;cnt&quot;:&quot;15&quot;},{&quot;value&quot;:&quot;Minecraft&quot;,&quot;cnt&quot;:&quot;4&quot;},{&quot;value&quot;:&quot;0000FF&quot;,&quot;cnt&quot;:&quot;3&quot;},{&quot;value&quot;:&quot;GUNDAM&quot;,&quot;cnt&quot;:&quot;2&quot;},{&quot;value&quot;:&quot;10086&quot;,&quot;cnt&quot;:&quot;2&quot;},{&quot;value&quot;:&quot;aaaaa&quot;,&quot;cnt&quot;:&quot;1&quot;},{&quot;value&quot;:&quot;333333&quot;,&quot;cnt&quot;:&quot;1&quo....
        /// </summary>
        internal static string bilibilicatalogy {
            get {
                return ResourceManager.GetString("bilibilicatalogy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;up&quot;:{&quot;keyword&quot;:[],&quot;user&quot;:[],&quot;rank&quot;:null}}.
        /// </summary>
        internal static string bilibilifilter {
            get {
                return ResourceManager.GetString("bilibilifilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;user&quot;:[],&quot;keyword&quot;:[{&quot;value&quot;:&quot;Yoooo&quot;,&quot;cnt&quot;:&quot;1339&quot;},{&quot;value&quot;:&quot;12dog&quot;,&quot;cnt&quot;:&quot;630&quot;},{&quot;value&quot;:&quot;fffff&quot;,&quot;cnt&quot;:&quot;431&quot;},{&quot;value&quot;:&quot;12dora&quot;,&quot;cnt&quot;:&quot;86&quot;},{&quot;value&quot;:&quot;PAPAPA&quot;,&quot;cnt&quot;:&quot;83&quot;},{&quot;value&quot;:&quot;10086&quot;,&quot;cnt&quot;:&quot;74&quot;},{&quot;value&quot;:&quot;china&quot;,&quot;cnt&quot;:&quot;70&quot;},{&quot;value&quot;:&quot;geass&quot;,&quot;cnt&quot;:&quot;67&quot;},{&quot;value&quot;:&quot;yyyyyy&quot;,&quot;cnt&quot;:&quot;64&quot;},{&quot;value&quot;:&quot;aaaaa&quot;,&quot;cnt&quot;:&quot;58&quot;},{&quot;value&quot;:&quot;BBBBB&quot;,&quot;cnt&quot;:&quot;43&quot;},{&quot;value&quot;:&quot;23333&quot;,&quot;cnt&quot;:&quot;39&quot;},{&quot;value&quot;:&quot;Madao&quot;,&quot;cnt&quot;:&quot;39&quot;},{&quot;value&quot;:&quot;hahaha&quot;,&quot;cnt&quot;:&quot;38&quot;},{&quo....
        /// </summary>
        internal static string bilibiliglobal {
            get {
                return ResourceManager.GetString("bilibiliglobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///&lt;title&gt;AcPlay&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;embed height=&quot;100%&quot; width=&quot;100%&quot; type=&quot;application/x-shockwave-flash&quot; pluginspage=&quot;http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash&quot;  AllowScriptAccess=&quot;always&quot; rel=&quot;noreferrer&quot; flashvars=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bilibilihtml {
            get {
                return ResourceManager.GetString("bilibilihtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ip&gt;127.0.0.1&lt;/ip&gt;
        ///&lt;country&gt;LAC&lt;/country&gt;
        ///&lt;login&gt;true&lt;/login&gt;
        ///&lt;name&gt;LACPlayer [本地]&lt;/name&gt;
        ///&lt;user&gt;10000&lt;/user&gt;
        ///&lt;scores&gt;0&lt;/scores&gt;
        ///&lt;money&gt;0&lt;/money&gt;
        ///&lt;face&gt;&lt;/face&gt;
        ///&lt;pwd&gt;00000000&lt;/pwd&gt;
        ///&lt;isadmin&gt;false&lt;/isadmin&gt;
        ///&lt;permission&gt;10000,1001&lt;/permission&gt;
        ///&lt;rank&gt;10000&lt;/rank&gt;
        ///&lt;level&gt;普通会员&lt;/level&gt;
        ///&lt;shot&gt;false&lt;/shot&gt;
        ///&lt;chatid&gt;10000&lt;/chatid&gt;
        ///&lt;vtype&gt;sina&lt;/vtype&gt;
        ///&lt;aid&gt;10000&lt;/aid&gt;
        ///&lt;typeid&gt;22&lt;/typeid&gt;
        ///&lt;pid&gt;1&lt;/pid&gt;
        ///&lt;click&gt;1&lt;/click&gt;
        ///&lt;favourites&gt;0&lt;/favourites&gt;
        ///&lt;credits&gt;0&lt;/credits&gt;
        ///&lt;coins&gt;0&lt;/coins&gt;
        ///&lt;fw_click&gt;1&lt;/fw_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bilibilimember {
            get {
                return ResourceManager.GetString("bilibilimember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;msg&gt;
        ///&lt;item bgcolor=&quot;#CCCCCC&quot; tooltip=&quot;点击反馈意见&quot;&gt;&lt;![CDATA[
        ///&lt;a href=&quot;http://acplay.loushao.net/&quot; target=&quot;_blank&quot;&gt;&lt;font color=&quot;#ffffff&quot;&gt;反馈意见&lt;/font&gt;&lt;/a&gt;
        ///]]&gt;&lt;/item&gt;
        ///&lt;/msg&gt;.
        /// </summary>
        internal static string bilibilimsg {
            get {
                return ResourceManager.GetString("bilibilimsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        /// &lt;PAD&gt;
        ///&lt;!-- &lt;scroll constv=&quot;true&quot; velocity=&quot;0.35&quot; /&gt; --&gt;
        ///&lt;rgg img=&quot;http://localhost5/blank.swf&quot; rggnum=&quot;1&quot; url=&quot;&quot; c=&quot;1&quot; /&gt;
        ///&lt;scroll constv=&quot;false&quot; delay=&quot;4000&quot; /&gt;
        ///  &lt;fade delay=&quot;3500&quot; alphaTo=&quot;1&quot; /&gt;
        ///  &lt;pool capacity=&quot;0&quot; /&gt;
        ///  &lt;keywords&gt; 
        ///  &lt;/keywords&gt;
        ///&lt;/PAD&gt;.
        /// </summary>
        internal static string bilibilipad {
            get {
                return ResourceManager.GetString("bilibilipad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string bilibiliplaytag {
            get {
                return ResourceManager.GetString("bilibiliplaytag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [].
        /// </summary>
        internal static string bilibilirolldate {
            get {
                return ResourceManager.GetString("bilibilirolldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;cross-domain-policy&gt;
        ///  &lt;allow-access-from domain=&quot;*&quot; /&gt;
        ///&lt;/cross-domain-policy&gt;.
        /// </summary>
        internal static string crossdomain {
            get {
                return ResourceManager.GetString("crossdomain", resourceCulture);
            }
        }
    }
}
